### ISSUE TITLE
xml ParseError - export_cda.xml

### ISSUE THREAD

**Issue by einzelfabrik** [simonkrenger/apple-health-to-fitbit#1]
Hello, I think the idea of your script is great - and have the same use case. Unfortunately it doesn't work as desired. Here is my setup.
I use an iPhone 8 with iOS 12.3.1, I work under windows 10.

After unpacking the health data. I executed the script:  **C:\>c:\Python\python.exe "D:\Export\health_to_fitbit.py" > "D:\Export\fitbit_format.csv"** then I get an error:

```
C:\>c:\Python\python.exe "D:\Export\health_to_fitbit.py" > "D:\Export\fitbit_format.csv“
Traceback (most recent call last):
  File "D:\Export\health_to_fitbit.py", line 7, in <modules>
    export_cda = ET.parse('D:\Export\export_cda.xml')
  File "c:\Python\lib\xml\etree\ElementTree.py", line 1197, in parse
    tree.parse(source, parser)
  File "c:\Python\lib\xml\etree\ElementTree.py", line 598, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: junk after document element: line 115, column 0
```

What can that be? an excerpt from export_cda.xml, 
```
113: </entry>
114: </ClinicalDocument>
115: <component>
 116: <section>
```
_About tips I am grateful_

**Comment by einzelfabrik** [comment]
Guten Morgen/Abend,
ich habe das Problem selber lösen können ursache war die Zeile 115 
`</ClinicalDocument>` in der Export_cda.xml
Ich habe diese Zeile ans Ende der Datei verschoben. und schon läuft der eigentliche Parse Prozess sauber durch. 
Zusätzlich habe ich die Pfade zu den Dateien direkt eingetragen!

Und ich habe den Datentyp von int in float in folgendem Abschnitt geändert:

```
if(record.get('type') == "HKQuantityTypeIdentifierFlightsClimbed"):
		if date_string in floors_dict:
			floors_dict[date_string] = float(floors_dict[date_string]) + float(value)
		else:
			floors_dict[date_string] = float(float(value))
```
Da ich sonst einen Fehler erhalten habe!
