### ISSUE TITLE
File not found error

### ISSUE THREAD

**Issue by JPSicotte** [simonkrenger/apple-health-to-fitbit#3]
Hi Simon, 

Thansk for putting together those codes.

Here's the error messagd that I receive once I'm executing the file through cmd on Windows. 

C:\Users\jpsicotte>AppData\Local\Microsoft\WindowsApps\python3.exe C:\Users\jpsicotte\Desktop\ddd\apple-health-to-fitbit-master\health_to_fitbit.py > fitbit_format.csv
Traceback (most recent call last):
  File "C:\Users\jpsicotte\Desktop\ddd\apple-health-to-fitbit-master\health_to_fitbit.py", line 7, in <module>
    export_cda = ET.parse('export_cda.xml')
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1264.0_x64__qbz5n2kfra8p0\lib\xml\etree\ElementTree.py", line 1197, in parse
    tree.parse(source, parser)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1264.0_x64__qbz5n2kfra8p0\lib\xml\etree\ElementTree.py", line 587, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'export_cda.xml'

I'm pretty new to the coding world, so It would be great if you can give me a hand resolving the issue. 

Thanks

**Comment by simonkrenger** [comment]
Dear @JPSicotte 

I have not tested the script on a Windows machine, however it should work as designed.
In your particular case, make sure you place both the `export_cda.xml` and the `export.xml` file in the same folder as the script (`C:\Users\jpsicotte\Desktop\ddd\apple-health-to-fitbit-master\` in your case).

**Comment by simonkrenger** [comment]
@JPSicotte any updates? Were you able to run the script?

**Comment by simonkrenger** [comment]
Closing this issue due to no activity.
